// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHeYT05B_NzqaV7gkELZRGvLOWBm_1pVg',
    appId: '1:629645260568:web:faeb5a9c1623213dd1d06d',
    messagingSenderId: '629645260568',
    projectId: 'transcollect-nnb-fr-hub',
    authDomain: 'transcollect-nnb-fr-hub.firebaseapp.com',
    storageBucket: 'transcollect-nnb-fr-hub.appspot.com',
    measurementId: 'G-MRWKGEQKTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSP59NllHUP9pzukolj8E4OgClIZGIK5k',
    appId: '1:629645260568:android:47b65a4434331e0ed1d06d',
    messagingSenderId: '629645260568',
    projectId: 'transcollect-nnb-fr-hub',
    storageBucket: 'transcollect-nnb-fr-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACI2MqOwVng-jteqRjjiwNyvgAxjKz-C0',
    appId: '1:629645260568:ios:91b1a8326daa5c3fd1d06d',
    messagingSenderId: '629645260568',
    projectId: 'transcollect-nnb-fr-hub',
    storageBucket: 'transcollect-nnb-fr-hub.appspot.com',
    iosBundleId: 'com.example.transcollectNnbFrHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACI2MqOwVng-jteqRjjiwNyvgAxjKz-C0',
    appId: '1:629645260568:ios:91b1a8326daa5c3fd1d06d',
    messagingSenderId: '629645260568',
    projectId: 'transcollect-nnb-fr-hub',
    storageBucket: 'transcollect-nnb-fr-hub.appspot.com',
    iosBundleId: 'com.example.transcollectNnbFrHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHeYT05B_NzqaV7gkELZRGvLOWBm_1pVg',
    appId: '1:629645260568:web:3df499505f4c30cfd1d06d',
    messagingSenderId: '629645260568',
    projectId: 'transcollect-nnb-fr-hub',
    authDomain: 'transcollect-nnb-fr-hub.firebaseapp.com',
    storageBucket: 'transcollect-nnb-fr-hub.appspot.com',
    measurementId: 'G-SPC43G651H',
  );

}